### ISSUE TITLE
Website is not available

### ISSUE THREAD

**Issue by SiamOfficial** [NYT92/husbando#1]
![image](https://github.com/NYT92/husbando/assets/76904970/870a52a9-7419-43b7-aed1-ffba982c53a1)
Is there any website or what?

**Comment by NYT92** [comment]
Sorry, my domain expired and I got no money right now but I already assigned my website to my new server

https://husbando.nyt92.eu.org

The images is still accessible by replacing ``i.husbando.pics`` to ``image-husbando.nyt92.eu.org`` but the data in the db might still using i.husbando.pics and I might edit all of them soon.
